//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FinalProject.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.Web;

    public partial class Cus
    {
        public int imageID { get; set; }
        public string title { get; set; }
        public string comment { get; set; }
        [DisplayName("Upload File")]

        public string imagePath { get; set; }
        
        public HttpPostedFileBase ImageFile { get; set; }

    }
}
